[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "echo 'Building Netlify functions...'"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[dev]
  functions = "netlify/functions"
  port = 8888
